[2025-04-06T13:34:52.630+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T13:34:52.639+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: premier_league_data_pipeline.download_data manual__2025-04-06T12:34:49.189703+00:00 [queued]>
[2025-04-06T13:34:52.644+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: premier_league_data_pipeline.download_data manual__2025-04-06T12:34:49.189703+00:00 [queued]>
[2025-04-06T13:34:52.645+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-06T13:34:52.656+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data> on 2025-04-06 12:34:49.189703+00:00
[2025-04-06T13:34:52.659+0100] {standard_task_runner.py:72} INFO - Started process 16807 to run task
[2025-04-06T13:34:52.662+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'premier_league_data_pipeline', 'download_data', 'manual__2025-04-06T12:34:49.189703+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/premier_league_dag.py', '--cfg-path', '/tmp/tmp2xiusv_h']
[2025-04-06T13:34:52.663+0100] {standard_task_runner.py:105} INFO - Job 5: Subtask download_data
[2025-04-06T13:34:52.695+0100] {task_command.py:467} INFO - Running <TaskInstance: premier_league_data_pipeline.download_data manual__2025-04-06T12:34:49.189703+00:00 [running]> on host dell-Latitude-5480
[2025-04-06T13:34:52.751+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Victory' AIRFLOW_CTX_DAG_ID='premier_league_data_pipeline' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T12:34:49.189703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T12:34:49.189703+00:00'
[2025-04-06T13:34:52.752+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T13:34:52.753+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T13:34:52.753+0100] {logging_mixin.py:190} INFO - Current task name:download_data state:running start_date:2025-04-06 12:34:52.639321+00:00
[2025-04-06T13:34:52.753+0100] {logging_mixin.py:190} INFO - Dag name:premier_league_data_pipeline and current dag run status:running
[2025-04-06T13:34:52.753+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T13:34:52.755+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 64, in _binary_paths
    raise ValueError(f"The path is not a valid file: {path}")
ValueError: The path is not a valid file: ../chromedriver-linux64/chromedriver

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/download_data.py", line 13, in download_data
    crawler = Crawler(season)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/crawler.py", line 21, in __init__
    self.driver = self._setup_driver()
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/crawler.py", line 28, in _setup_driver
    driver = webdriver.Chrome(service=service)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    if finder.get_browser_path():
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-06T13:34:52.764+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T13:34:52.764+0100] {logging_mixin.py:190} INFO - Task start:2025-04-06 12:34:52.639321+00:00 end:2025-04-06 12:34:52.763735+00:00 duration:0.124414
[2025-04-06T13:34:52.764+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_data> dag:<DAG: premier_league_data_pipeline> dagrun:<DagRun premier_league_data_pipeline @ 2025-04-06 12:34:49.189703+00:00: manual__2025-04-06T12:34:49.189703+00:00, state:running, queued_at: 2025-04-06 12:34:49.202756+00:00. externally triggered: True>
[2025-04-06T13:34:52.764+0100] {logging_mixin.py:190} INFO - Failure caused by Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2025-04-06T13:34:52.765+0100] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=premier_league_data_pipeline, task_id=download_data, run_id=manual__2025-04-06T12:34:49.189703+00:00, execution_date=20250406T123449, start_date=20250406T123452, end_date=20250406T123452
[2025-04-06T13:34:52.782+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T13:34:52.783+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task download_data (Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
; 16807)
Traceback (most recent call last):
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 64, in _binary_paths
    raise ValueError(f"The path is not a valid file: {path}")
ValueError: The path is not a valid file: ../chromedriver-linux64/chromedriver

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/download_data.py", line 13, in download_data
    crawler = Crawler(season)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/crawler.py", line 21, in __init__
    self.driver = self._setup_driver()
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/airflow/dags/scripts/crawler.py", line 28, in _setup_driver
    driver = webdriver.Chrome(service=service)
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    if finder.get_browser_path():
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "/home/Data_Professional/PycharmProjects/DE_Zoomcamp_Capstone_Project/.venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-06T13:34:52.794+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T13:34:52.829+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T13:34:52.829+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
